# Site settings
title: PY的个人博客
description: "A blog about PY ..."
baseurl: ""
url: "http://www.pengy.tech" 
username: PY
user_title: PY - JUST FOR FUN~
email: pengyang813@foxmail.com
github_username:  pppppY

# Build settings
markdown: kramdown
paginate: 3
gems: [jekyll-paginate]
paginate_path: "/page/:num"